### ISSUE TITLE
Home Page issues

### ISSUE THREAD

**Issue by kpierduta** [kpierduta/deckerdence-website#34]
- [x] Boxes in the table to be the same height
- [x] Make sure where the price is, is level across all 3 boxes

![Screenshot 2022-02-21 at 10 01 10](https://user-images.githubusercontent.com/40568273/154932814-ca65e6b3-ad5a-41ad-a346-97b79e9aaa8c.png)

- [x] Can we link this below section so that it is clickable and set up to go to a page of our choice
![Screenshot 2022-02-21 at 10 34 52](https://user-images.githubusercontent.com/40568273/154938303-8667cf93-f5a9-4fbb-b069-53a14caad668.png)

- [x] Need to be able to update table in Sanity
![Screenshot 2022-02-21 at 10 41 28](https://user-images.githubusercontent.com/40568273/154939364-1a0c412b-897e-448b-8a25-042fd085d31e.png)
![Screenshot 2022-02-21 at 10 41 32](https://user-images.githubusercontent.com/40568273/154939367-403f26d4-1389-4844-98fd-f051964cb6a5.png)

- [x] Background colour should be #94272F (As per Figma) and writing should be white.
![Screenshot 2022-02-21 at 12 15 59](https://user-images.githubusercontent.com/40568273/154953908-5fbd2e6d-09ed-4026-bcd7-1296d6ebc4f8.png)

- [x] Block not designed as per FIgma. Figma on left - development on right. For example, background should be light grey etc etc - please check Figma
![Screenshot 2022-02-21 at 12 19 07](https://user-images.githubusercontent.com/40568273/154954070-825abddd-e823-473f-87f0-56e1b9fde3d2.png)

- [x] Can the formatting typed in Sanity reflect on front end, please?
<img width="607" alt="Screenshot 2022-02-21 at 12 25 24" src="https://user-images.githubusercontent.com/40568273/154955038-4a64d868-9a19-4090-aa98-2278e49451d8.png">

![Screenshot 2022-02-21 at 12 25 27](https://user-images.githubusercontent.com/40568273/154955069-ac8e0ea3-4296-473f-8561-b00d8066c450.png)

- [x] Owner component block not working
![Screenshot 2022-02-21 at 12 42 38](https://user-images.githubusercontent.com/40568273/154957452-dfc9b21b-0704-4a5c-a497-44b6ba0b4c69.png)
![Screenshot 2022-02-21 at 12 42 47](https://user-images.githubusercontent.com/40568273/154957467-52b91ae8-9903-4873-a854-290d2a262490.png)

- [x] Components aren't full width on bigger screens (some CTAs aren't and the hero images aren't)
![Screenshot 2022-02-21 at 12 44 59](https://user-images.githubusercontent.com/40568273/154957764-977d1d5d-6898-40b7-bbbe-5c50c7969bbc.png)

**Comment by gagansaini1212** [comment]
@kpierduta All the issues mentioned above are completed. Please have a look.
