### ISSUE TITLE
Hire Options - Component/block based

### ISSUE THREAD

**Issue by kpierduta** [kpierduta/deckerdence-website#36]
- [x] Convert hire pages to be block-based. Most components are already built on other pages.

![Screenshot 2022-03-04 at 13 01 17](https://user-images.githubusercontent.com/40568273/156793371-3b0999c8-9c3e-4cc4-a575-efd47ab7d3da.png)

- [x] 2 new components needed are:

![Screenshot 2022-03-04 at 13 02 25](https://user-images.githubusercontent.com/40568273/156793444-395e2997-4fc5-4ed2-819e-357d11cd3134.png)

![Screenshot 2022-03-04 at 13 02 06](https://user-images.githubusercontent.com/40568273/156793452-47218387-d6ce-4175-837b-d03b32818f8d.png)

**Comment by gagansaini1212** [comment]
@kpierduta Info Card Block and Category Block added respectively to the issues mentioned.

**Comment by kpierduta** [comment]
Thank you @gagansaini1212
