### ISSUE TITLE
Final issues

### ISSUE THREAD

**Issue by DCConnor** [kpierduta/deckerdence-website#37]
Hi, @dharmveer97 

- [x] On the deckerdence branch V2, the component below doesn't seem to be pulling through? Could you take a look for me, please?

![image](https://user-images.githubusercontent.com/100126342/157435283-06717cad-b792-4540-9c80-96569c08780e.png)

- [x] Also, if possible can you remove the download component from V2 as well! 

![image](https://user-images.githubusercontent.com/100126342/157435512-40795c3e-8a21-43c1-8172-799ff50ed1c0.png)

Thank you in advance

**Comment by DCConnor** [comment]
Hi, @dharmveer97 

- [ ] Could you make it possible for us to be able to set the button target for the learn more buttons, please?

![image](https://user-images.githubusercontent.com/100126342/157451663-451829a5-2034-456b-ad41-e30634696ddc.png)

Thank you!

**Comment by DCConnor** [comment]
Hi, @dharmveer97 

- [ ] At the moment the table block component in the hire option page only allows us to tick all boxes or none at all, can you make it so we are able to control which box is ticked or not? Also, the ultimate deckerdence box is spelt incorrect "Decerdence" instead of deckerdence. (Please see the above table for reference) 

<img width="953" alt="image" src="https://user-images.githubusercontent.com/100126342/157462383-4ffc6744-238c-4b16-ad45-0c53d470b50c.png">

Thank you

**Comment by DCConnor** [comment]
Hi, @dharmveer97 @gagansaini1212 

- [ ] Can you remove both the hire page and the main page section because we have multiple of the same pages in sanity now! We have recreated the content of these pages into the pages tab instead! 

![image](https://user-images.githubusercontent.com/100126342/157642171-12167663-5cdd-4959-aec6-41cfb5d1194c.png)

Thank you

**Comment by kpierduta** [comment]
- [ ] Writing on information hover on the table is too small
- [ ] No padding has been applied to the hover over - see actual and Figma design below

<img width="558" alt="Screenshot 2022-03-13 at 14 41 35" src="https://user-images.githubusercontent.com/40568273/158064886-554d93b1-3db3-4883-831d-cb024e83e9dd.png">

<img width="1120" alt="Screenshot 2022-03-13 at 14 43 31" src="https://user-images.githubusercontent.com/40568273/158064917-131cc8fd-fbec-4a90-97da-7c011182a270.png">

**Comment by kpierduta** [comment]
- [ ] Make sure all paragraph text is consistent/ same font size - make it an in between size between the 2 examples below

**Text too small**
<img width="1196" alt="Screenshot 2022-03-13 at 14 45 08" src="https://user-images.githubusercontent.com/40568273/158065056-b3f332c9-0032-4c4b-a4cc-f1bf5663834a.png">

**Text too big:**
<img width="974" alt="Screenshot 2022-03-13 at 14 45 23" src="https://user-images.githubusercontent.com/40568273/158065072-14293f22-0afc-49f1-8681-09738e25b03a.png">

**Comment by kpierduta** [comment]
- [ ] Need to be able to update the images in this component - do not connect them. Manual image upload please

<img width="1385" alt="Screenshot 2022-03-13 at 14 24 44" src="https://user-images.githubusercontent.com/40568273/158065193-26f97c1d-7e18-415c-b061-ab498de2cc0a.png">

<img width="1221" alt="Screenshot 2022-03-13 at 14 27 39" src="https://user-images.githubusercontent.com/40568273/158065199-c6eaefce-7fc1-42c2-a221-33a9ac66e150.png">

<img width="782" alt="Screenshot 2022-03-13 at 14 27 04" src="https://user-images.githubusercontent.com/40568273/158065202-81175ab9-99b4-4161-b905-2bb179267d1f.png">

**Comment by kpierduta** [comment]
- [ ] Button text and call to action text should all be the same - in the photo Find Out More - should be all capital and have the same formatting as the 'BOOK A CALL WITH US' below it - this change is site wide. Make sure all buttons and formatting of button text is uppercase, the same weight, the same size, the same padding.

<img width="1440" alt="Screenshot 2022-03-13 at 15 23 32" src="https://user-images.githubusercontent.com/40568273/158066861-c629d567-a814-44ec-bbcb-d637af261c20.png">

**Comment by kpierduta** [comment]
- [ ] Text in about section isn't formatting the paragraphs 
- [ ] Person's name slightly overlapping design

<img width="1434" alt="Screenshot 2022-03-13 at 15 41 04" src="https://user-images.githubusercontent.com/40568273/158067546-b8f37cce-73f8-4e3f-a057-dc5c474f7ceb.png">

<img width="1440" alt="Screenshot 2022-03-13 at 15 41 45" src="https://user-images.githubusercontent.com/40568273/158067554-ea55a796-838a-4821-b59c-06e74fe535ed.png">

**Comment by kpierduta** [comment]
<img width="1440" alt="Screenshot 2022-03-13 at 15 45 01" src="https://user-images.githubusercontent.com/40568273/158067659-b3c9c9f8-0532-4f85-ae14-dcf58fcc2ffb.png">

<img width="1440" alt="Screenshot 2022-03-13 at 15 44 36" src="https://user-images.githubusercontent.com/40568273/158067652-1331ac4f-765b-4acb-b27d-a827515b1ca1.png">

**Comment by gagansaini1212** [comment]
> 

Hi @DCConnor , You can control table ticks. If you add nothing in the table tick will be shown and if you write any text then the text will appear but by just adding empty space with the spacebar key of the keyboard there will be nothing displayed. I set one demonstration for you on the home page for "Classic Deckerdence" field.

**Comment by gagansaini1212** [comment]
> Hi, @dharmveer97
> 
> * [x]  At the moment the table block component in the hire option page only allows us to tick all boxes or none at all, can you make it so we are able to control which box is ticked or not? Also, the ultimate deckerdence box is spelt incorrect "Decerdence" instead of deckerdence. (Please see the above table for reference)
> 
> <img alt="image" width="953" src="https://user-images.githubusercontent.com/100126342/157462383-4ffc6744-238c-4b16-ad45-0c53d470b50c.png">
> 
> Thank you

Hi @DCConnor , You can control table ticks. If you add nothing in the table tick will be shown and if you write any text then the text will appear but by just adding empty space with the spacebar key of the keyboard there will be nothing displayed. I set one demonstration for you on the home page for "Classic Deckerdence" field.
